### ISSUE TITLE
Image UI fields remain when they shouldn't

### ISSUE THREAD

**Issue by mattwiebe** [crowdfavorite/wp-post-formats#1]
If you activate any format with an image field (featured image or gallery fields) and return to either the Aside or Link formats, the image-related fields remain visible.

**Comment by alexkingorg** [comment]
Can you provide steps to reproduce?

**Comment by mattwiebe** [comment]
Hey Alex, sorry I wasn't more clear. Reproduction: 
1. Click on either Image or Gallery tabs.
2. Click on Link or Aside tab
3. The image-related fields (Featured Image or Gallery) remain when they should be hidden.

After further investigation, there were two actual issues here (both fixed in pull request #2):
1. The `CF.postFormats.link()` function had a selector typo, so it wasn't hiding what it should.
2. You don't explicitly support the aside format, so whatever fields were previously showing remained. (This would also be true of the other formats that aren't explicitly supported with their own fields: aside, audio, chat. Any undefined ones will simply call `CF.postFormats.standard()` to return to just the post title.

**Comment by alexkingorg** [comment]
We chose not to support Asides in our initial implementation because we find them confusing with Link posts. What should an Aside do? Should it have custom fields?

So yeah, that's probably the main thing that needs to be figured out.

**Comment by mattwiebe** [comment]
I agree: asides are weird. I think the codex page suggests not showing the title on the front end. Both Twenty Ten and Twenty Eleven use asides - they don't show title in a loop, but do on a single post.

In any case, my patch punts this for now by just allowing currently non-UI'd formats (aside, audio, chat) to just show the title and hide other fields when switched to.

**Comment by blogan** [comment]
I think as good a description of asides as anywhere is this Matt Mullenweg post from 2004

http://ma.tt/2004/05/asides/

This predates Twitter and Facebook (at least for the masses) so there is now a huge overlap between status and asides. I'd still like both, with a status being a short note about me and an aside being a short note about _anything_.

**Comment by alexkingorg** [comment]
This should be resolved, continuing discussion of #5 in that thread.
