### ISSUE TITLE
Quote format and book quotes

### ISSUE THREAD

**Issue by mattwiebe** [crowdfavorite/wp-post-formats#10]
I was thinking about using the quote format to put in a quote from a book. But where do I put the book reference? Obviously not the Source URL field, as it's not a URL. I could append it in the source name, but that's not entirely obvious either.

I don't have a great solution for this yet, just wanted to register it as an issue that might warrant attention. I'll keep thinking it over.

**Comment by alexkingorg** [comment]
I think adding hooks (as done in this commit) is the best solution for extensibility.
