### ISSUE TITLE
The autogenerated titles should also work for the post slugs

### ISSUE THREAD

**Issue by peroyomas** [crowdfavorite/wp-post-formats#11]
I tested the plugin and seems that the autogenerated titles don't work with the post slugs, unlike the P2 theme, which causes problems sometimes due to a WordPress bug with 'ID number' slugs that seems isn't going to be fixed anytime soon.

**Comment by alexkingorg** [comment]
What bug? I'm not seeing any issues with this functionality.

**Comment by peroyomas** [comment]
Mentioned in this WP trac issue http://core.trac.wordpress.org/ticket/5305 . The permalinks became broken when the post slug is the same as the post id and one is using a custom prefix in permalinks along "post_name" rather than "post_id" (like "/articles/%post_name%").

My request, regarding this plugin, is that the slugs could also be "auto-generated", just like the titles are.

**Comment by alexkingorg** [comment]
I'll flag this for future consideration, but don't intend to make the change at this time. You're very welcome to fork or create a plugin that does this.
