### ISSUE TITLE
Displaying post formats properly on feeds

### ISSUE THREAD

**Issue by peroyomas** [crowdfavorite/wp-post-formats#13]
By default, the WordPress RSS feeds shows the Author, the date, the title and the body content, but not the custom fields. I guess the plugin may help to solve that regarding post formats (which may or may not be related to the "fallback" plugin).

---

All formats:

The title has to be the default title field were available. If the format don't support a title field or the user forgot to add something, it gets auto-filled with the first characters of whatever the "body" content is. If there's _no text anywhere_ (not a good practice, yet very common with photos and videos), the title resorts to the name of the format (like, "image" or "video")

---

Audio / Video / Image:

The "body" is the embedded content followed by the rest.

---

Quote:

The "body" is the quote, followed by the citation. I believe is fine to leave it with the raw unformatted text, unless is for semantic purposes (like puttting the quote in a "blockquote" tag).

---

Chat:

The "body" is the chat. I believe is fine to leave it with the raw unformatted text, unless is for semantic purposes.

---

Status / Aside:

The "body" is the text. Title appears as defined above.

---

Link:
Title appears as defined above, Then, the body _repeats_ the title with the link markup, followed by the rest of the text.

I've seen many people tweaking feeds by making the feed "post" permalink redirect to the post 'link' instead, yet I guess is somewhat confusing most of the time.

---

Gallery:

Tumblr threats these ('photosets') by merely showing all the images in succession and the rest of the text, yet many people prefer to only add a thumbnail and left the complete gallery "after the jump". I'm more with the first option, but still.

**Comment by alexkingorg** [comment]
This plugin creates an admin interface only.
