### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by jasonhobbsllc** [crowdfavorite/wp-post-formats#15]
Just curious how I use this in my child theme I am creating?

Download the zip file and then add it to?

I am sure this is common knowledge to most but not to me. :)

Thanks for any help!

**Comment by saddam-azad** [comment]
Actually, many of us are thinking the same thing. A little starter guide would be fantastic.

I know this is meant for developers who are supposed to know what they are doing, but there are some of us who needs a little Getting Started guide. We have all been newbies at some point.

Alex, would you mind spending 5 minutes on a basic README.md? Thanks.

**Comment by alexkingorg** [comment]
Seems like a great way for you to contribute to the project...

**Comment by saddam-azad** [comment]
Actually, I am having difficulty getting started myself.

Would you please point us in the right direction? Thanks in advance.
