### ISSUE TITLE
Quote appends excerpt to post field

### ISSUE THREAD

**Issue by blogan** [crowdfavorite/wp-post-formats#18]
When saving a quote formatted post, the custom excerpt gets appended to the post field.

**Comment by alexkingorg** [comment]
Can you describe this in more detail? Steps to reproduce and more information about the problem you're seeing would be helpful.

**Comment by blogan** [comment]
It looks like this issue has been fixed. I downloaded the latest version and then tried to recreate the issue and was not able to.
