### ISSUE TITLE
integrate into theme

### ISSUE THREAD

**Issue by ghost** [crowdfavorite/wp-post-formats#26]
hi how to integrate plugin into theme like :
require ( get_template_directory() . '/includes/crowdfavorite-wp-post-formats-5718433/cf-post-formats.php' 
is it possible?

**Comment by FutureMedia** [comment]
Same question here. Which is best way to include the plugin's functionality in a theme that will be distributed for free?

**Comment by pdewouters** [comment]
Create a subfolder in your theme.
Put all the files folders from this repo in there.
In functions.php, you can filter the plugin base URL:
https://gist.github.com/3945797

**Comment by jondavidjohn** [comment]
http://alexking.org/blog/2012/07/09/include-plugin-in-wordpress-theme

**Comment by pdewouters** [comment]
thanks @jondavidjohn , I updated the gist accordingly

**Comment by FutureMedia** [comment]
Sorry, but the suggested code is not working, at least in my case.

**Comment by FutureMedia** [comment]
Ok, I found what was missing. The filter function for the new address:

function change_cfpf_base_url() {
    return get_template_directory_uri().'/inc/plugins/wp-post-formats/';
}
