### ISSUE TITLE
Gallery preview not showing images

### ISSUE THREAD

**Issue by stevebluck** [crowdfavorite/wp-post-formats#32]
When using WP 3.5, creating a new post and adding images to the gallery format works fine. Apart from the preview images never get displayed and the the loading spinner stays put like so: http://cl.ly/LauS

After saving the post, the gallery format stays like this restricting me to have the ability to upload images with the gallery format image upload button.

Is there something I'm missing?

**Comment by alexkingorg** [comment]
What version?

**Comment by stevebluck** [comment]
I'm using 1.1. And testing on MAMP. 

Cheers.

**Comment by alexkingorg** [comment]
I can't seem to reproduce this.

**Comment by stevebluck** [comment]
I can confirm that it is only doing it locally on Mamp, when uploading to my host it works fine.

**Comment by hchouhan** [comment]
Hello,
The issue is also when tested on WAMP.

**Comment by Pushplaybang** [comment]
Anyone know why ti does this on mamp ? would be great to understand it so we can try and figure out a work around
