### ISSUE TITLE
Managing and Displaying Audio and Video  

### ISSUE THREAD

**Issue by Pushplaybang** [crowdfavorite/wp-post-formats#34]
While I'm clear that this plugin creates the admin interface only, I've been in a bit of a quandry around how best to handle this media on the front end,  which has brought up some backend considerations as well.  

Ideally these Post formats should be functional in the following 3 cases.
1.  Embed code provided by third party (ie: the youtube iframe)
   --  This is both easy to insert and easy to render in a template, currently
2.  Direct Link  (Oembed) 
   -- handling this is not really difficult, but the challenge is in determining whether its an Iframe  / embed etc or a link and handling the returned value on the front end appropriately - kind of a front end concern I don't think is relevant to the admin interface.
3.  handling local media from the media library.
   --hmmm.... open the media library - insert into post, cut from post to meta-box and then handle as in point two ?

I was originally thinking it may make sense to add a switch between embed field and a media uploader, considered using just the media uploader, but that doesn't seem to support inserting the embed code.....  

Thoughts on how we could improve the UI  ? 

Sidenote :  If anyones interested or struggling with detecting whats been added to the meta box and handling the media properly on the front end  - I added this snippet that should get you started....  https://gist.github.com/4578072

**Comment by alexkingorg** [comment]
I don't understand what this issue is intended to accomplish...

**Comment by Pushplaybang** [comment]
regarding the meta boxes for audio and video.It seems a little clumsy to add locally stored media, or in fact upload media as described in point three above.I think it would be ueber cool if there was an easy way to switch between the embed box and a media uploader for these post formats, and wanted to get a general feel for whether anyone else thought this would be a cool feature.

**Comment by Pushplaybang** [comment]
You know, kinda exactly whats now shown up in the beta for WP 3.6.
