### ISSUE TITLE
render media in the back end.

### ISSUE THREAD

**Issue by Pushplaybang** [crowdfavorite/wp-post-formats#35]
I think it would be a pretty cool enhancement to actually display the audio / video media in the backend in the same way that the featured image or gallery is displayed.

Anyone else interested in this as an enhancement ?  

I'm a bit of noob when it comes to dev in the admin section of wp so would love input from other users / alex if there is interest but also quite keen to take a few stabs at this.

I reckon this could be done in two way, either rendering the media with some ajax voodoo - possibly overkill, or after saving which I think is probably a bit easier to do.

**Comment by alexkingorg** [comment]
Audio requires additional plugins, video would slow down the rendering of the admin. I'm inclined to take no action on this.

**Comment by Pushplaybang** [comment]
thats fair  - I didn't consider that.  An additional js plugin would be needed for local video as well I suppose, so the overhead would grow noticeably on page load.  Thought it would be pretty sweet initially but agreed.
