### ISSUE TITLE
Making Title field visible for Status & Quote Post formats

### ISSUE THREAD

**Issue by hchouhan** [crowdfavorite/wp-post-formats#38]
Hello,

Can anyone please guide me on how to make the default Title field visible for the Post formats - Quote & Status. 
The reason for asking this is in new WordPress 3.6 that is currently being developed these fields are visible.

**Comment by hchouhan** [comment]
Hello,

I have been able to do the above. Also I have tried to keep fields same as the upcoming WordPress version 3.6. If anyone wants the code let me know.

**Comment by rahulkashyapknl** [comment]
hello @hchouhan  bro can u say me how can i use Status format in my the for outupt if you have any code for it show plz tell me

**Comment by hchouhan** [comment]
Hi @rahulkashyapknl, I'm not sure what your exact question is. Can you please describe more thoroughly.

**Comment by rahulkashyapknl** [comment]
@hchouhan  bro if you know how to get output of Status post format in wordpress theme so please let me say. i will thankful to u :)

**Comment by hchouhan** [comment]
@rahulkashyapknl I'm afraid I do not have any code with me, as after the work of integration was discontinued mid-way in WordPress 3.8 beta, I updated all my code to simply rely on existing features. Instead of using a plugin with too many custom meta, I would suggest looking at http://themehybrid.com/themes/socially-awkward. The Hybrid core framework has many helpers to allow custom styling to different post types. These include finding video / audio embed and displaying them before post title etc. The end looks are similar to using custom meta like this plugin.
