### ISSUE TITLE
Gallery Format

### ISSUE THREAD

**Issue by hirstmusic** [crowdfavorite/wp-post-formats#39]
First of all, I love WP Post Formats and can't wait until WordPress 3.6 is released. But for now, I'm working on building a custom theme and just don't understand how to display the Gallery Format to the end user.

The rest of the formats make sense and I've been able to work with them beautifully. For instance, I use <?php echo get_post_meta($post->ID, '_format_audio_embed', true);?> to fetch the embed code from the Audio Format for use in format-audio.php.

But the Gallery is just killing me and I can't figure out what code I should be using to display the uploaded images in any kind of unique way.

I click "Upload Images" and can choose images to either Insert into Post or create a Gallery. But this doesn't appear any different than the standard "Add Media" button. So I'm sure I'm missing something... :\

Ultimately, I'd like to wrap the gallery images into FlexSlider. But I think I need a better understanding of how to display the Gallery images first.

Thanks for all you've done with this exceptional plugin!

**Comment by alvisir** [comment]
Hi, if you're using MAMP o WAMP to develop your theme,  you should read this issue https://github.com/crowdfavorite/wp-post-formats/issues/32 .
As for your last point, this link might be useful to you -> http://wordpress.stackexchange.com/questions/54989/get-image-from-posts-gallery

Cheers
