### ISSUE TITLE
Gallery sorting

### ISSUE THREAD

**Issue by modulbuero** [crowdfavorite/wp-post-formats#40]
Hi,

is it possible to sort the images in a Gallery after adding them? Like just a drag'n'drop to reorder the images. I almost was sure that this used to work, but when i tried it, it doesn't work.

Thanks for your good work, i really like this plugin.

By the way: Do you have any plans for WP 3.6? Does this plugin work with the new interface? Or do you plan to replace the new interface with yours?

Best,

Christian

**Comment by alexkingorg** [comment]
You can sort the Image order in the media popover.

We are in "wait and see" mode for WP 3.6 - things are very much in flux there.

**Comment by modulbuero** [comment]
I'm sorry to have to bug you again, but i can't find what you meant. When i click on "Upload Images", i don't find a place anywhere where i have either a input field for a number to sort the image by nor do the images sort by drag'n'drop. The same thing is when i click on the "Upload Images" above the editor itself. I'm on WP 3.5.1 and CF 1.1. Could you give me a hint? Thanks!

**Comment by modulbuero** [comment]
Never mind, i found it. You have to select only the images uploaded to this post. This enables the drag'n'drop-sorting. Thanks for your help!
