### ISSUE TITLE
Some post formats not implemented

### ISSUE THREAD

**Issue by blogan** [crowdfavorite/wp-post-formats#5]
The WordPress codex lists some post formats: http://codex.wordpress.org/Post_Formats

Of these, wp-post-formats doesn't appear to implement:
1. asides
2. audio
3. chat

It would seem now is the perfect time to develop the standard.

**Comment by alexkingorg** [comment]
Do you have suggestions for how these should be handled?

**Comment by blogan** [comment]
In my opinion:

Asides should be handled like statuses: a post with no title.
Audio should be handled like video: add a custom field for a URL to the audio file. 
Chat ??? I have no idea. I only mentioned it because it's mentioned in the Codex. I've never seen chants posted.

**Comment by alexkingorg** [comment]
If [Asides need titles in single post pages](https://github.com/crowdfavorite/wp-post-formats/issues/1#issuecomment-2533724), we probably need to show the title.

**Comment by blogan** [comment]
Would that also apply to Statuses, or do Statuses not get displayed in single post pages?

**Comment by alexkingorg** [comment]
Statuses have single views, but not titles.

I've implemented initial support for other formats (includes audio embed field), please open future tickets for discussion on a  specific format.
